"""initial schema

Revision ID: 41af6e00a200
Revises: 
Create Date: 2026-06-14 22:13:12.889572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41af6e00a200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('home_team_code', sa.String(length=3), nullable=True),
    sa.Column('away_team_code', sa.String(length=3), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('external_ref', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINISHED', name='matchstatus'), nullable=False),
    sa.Column('stage', sa.Enum('GROUP', 'R16', 'QF', 'SF', 'FINAL', name='matchstage'), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('advancing_team', sa.Enum('HOME', 'DRAW', 'AWAY', name='betchoice'), nullable=True),
    sa.Column('ai_home_win_prob', sa.Float(), nullable=True),
    sa.Column('ai_draw_prob', sa.Float(), nullable=True),
    sa.Column('ai_away_win_prob', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('public_home_pct', sa.Float(), nullable=True),
    sa.Column('public_draw_pct', sa.Float(), nullable=True),
    sa.Column('public_away_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_kickoff_time'), ['kickoff_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sso_provider', sa.String(length=20), nullable=True),
    sa.Column('sso_subject', sa.String(length=128), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('double_cards', sa.Integer(), nullable=False),
    sa.Column('insurance_cards', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('predicted_result', sa.Enum('HOME', 'DRAW', 'AWAY', name='betchoice'), nullable=False),
    sa.Column('predicted_home_score', sa.Integer(), nullable=True),
    sa.Column('predicted_away_score', sa.Integer(), nullable=True),
    sa.Column('use_double_card', sa.Boolean(), nullable=False),
    sa.Column('use_insurance_card', sa.Boolean(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('exact_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_user_match_bet')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_user_id'), ['user_id'], unique=False)

    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_invite_code'), ['invite_code'], unique=True)

    op.create_table('league_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_league_user')
    )
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_members_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_members_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_league_members_league_id'))

    op.drop_table('league_members')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_invite_code'))

    op.drop_table('leagues')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_user_id'))
        batch_op.drop_index(batch_op.f('ix_bets_match_id'))

    op.drop_table('bets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_kickoff_time'))

    op.drop_table('matches')
    # ### end Alembic commands ###
